name: "Publish addon"

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - - name: Login to image repository
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AKM_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --armhf --armv7 \
            --target /data \
            --docker-hub rfc1149
